#!/usr/bin/python

print 'Content-Type: text/plain'
print ''

import cgi
import forex
import datetime


def get_val (name):
    if cgi.FieldStorage ()['pair1']:
        return cgi.FieldStorage ()[name].value
    else:
        print 'Error: parameter %s not given' % name
        exit (0)


def format_date (d):
    return "%d.%02d.%02d" % (d.year, d.month, d.day)


def format_time (d):
    return "%02d:%02d" % (d.hour, d.minute)


fx = forex.FXFetcher ()

data = fx.fetch (get_val ('pair1').upper (), get_val ('pair2').upper (), get_val ('period').upper (), int (get_val ('bars')))

print "timestamp,date,time,open,high,low,close"

for ts, bar in zip (data['time'], data['data']):
    d = datetime.datetime.fromtimestamp (ts)
    # do not show weekend data
    if d.weekday () in [5,6]:
        continue
    print "%d,%s,%s,%s,%s,%s,%s" % (ts, format_date (d), format_time (d), bar['O'], bar['H'], bar['L'], bar['C'])
