#!/usr/bin/python

print 'Content-Type: text/calendar; charset=UTF-8'
print 'Cache-Control: no-cache, must-revalidate'
print 'Expires: Sat, 26 Jul 1997 05:00:00 GMT'
print ''

from icalendar import Calendar, Event, UTC
import time
import datetime
import news
from google.appengine.ext import db

d_from = datetime.date.today ()
d_to = d_from + datetime.timedelta (days = 7)

cal = Calendar ()
cal['prodid'] = "-//Shmuma//FX News 0.1//EN"
cal['version'] = "2.0"
cal['x-wr-timezone'] = "UTC"
cal['x-wr-calname'] = "Forex News"
cal['x-wr-caldesc'] = "Upcoming financial news"
cal['x-published-ttl'] = "P1H"


def norm_str (str, vis = 0):
    if vis == 0:
        if str == None:
            return "-"
        return str.strip ()
    else:
        if str == None:
            return ""
        return str.strip ()



q = db.GqlQuery ("select * from News_Record where when > :1 and when < :2 order by when", d_from, d_to)

for ev in q:
    event = Event ()
    event['uid'] = "%d-%d@quote-tracker.appspot.ru" % (ev.id, time.mktime (ev.when.timetuple ()))
    event['summary'] = "%s, Prev: %s, Fore: %s, Curr: %s" % (norm_str (ev.name), norm_str (ev.pred),
                                                             norm_str (ev.fore), norm_str (ev.curr))
    event['dtstamp'] = ev.when
#    event['dtstart'] = ev.when
#    event['dtend'] = ev.when + datetime.timedelta (minutes = 10)
    event['prioeity'] = 0
    cal.add_component (event)


print cal.as_string ()
