#!/usr/bin/python

import datetime
import string
from news import *
from google.appengine.ext import db
from google.appengine.ext.webapp import template
from google.appengine.ext import webapp
from google.appengine.ext.webapp.util import run_wsgi_app


def norm_str (str):
    if str == None:
        return "-"
    return '"%s"' % str.strip ()



class NewsPage (webapp.RequestHandler):
    def get (self):
        if self.request.get ("csv"):
            self.response.headers['Content-Type'] = 'text/plain; charset=utf-8'
            self.response.out.write ("id,date,time,score,name,name_ru,country,prev,fore,fact,curr\n")
            q = db.GqlQuery ("select * from News_Record where when > :1 order by when", datetime.date.today ())
            for ev in q:
                self.response.out.write ("%d,%s,%s,%d,%s,%s,%s,%s,%s,%s,%s\n" % (ev.id, ev.when.date ().isoformat (), ev.when.time ().isoformat (),
                                                                                 ev.score, norm_str (ev.name), norm_str (ev.name_ru), norm_str (ev.country),
                                                                                 norm_str (ev.pred), norm_str (ev.fore), 
                                                                                 norm_str (ev.fact), norm_str (ev.curr)))

app = webapp.WSGIApplication ([('/news', NewsPage)], debug=True)

def main ():
    run_wsgi_app (app)

if __name__ == "__main__":
    main ()
