#!/usr/bin/python

print 'Content-Type: text/calendar'
print ''

from icalendar import Calendar, Event, UTC
from datetime import datetime

cal = Calendar ()

cal.add ('prodid', "-//Shmuma//FX News")
cal.add ('version', "0.1")

event = Event ()
event.add ('summary', "Building index")
event.add('dtstamp', datetime(2010,9,2,9,30,0,tzinfo=UTC))
event.add('dtstart', datetime(2010,9,2,9,30,0,tzinfo=UTC))
event.add('dtend', datetime(2010,9,2,9,35,0,tzinfo=UTC))
event['uid'] = '20100902093000/BI@shmuma.ru'
event.add('priority', 5)

#event = Event ()
#event.add ('summary', "Building index")
#event.add('dtstamp', datetime(2010,9,2,9,30,0,tzinfo=UTC))
#event.add('priority', 5)

#event = Event ()
#event.add ('summary', "Building index")
#event.add('dtstamp', datetime(2010,9,2,9,30,0,tzinfo=UTC))
#event.add('priority', 5)

cal.add_component (event)

print cal.as_string ()
