#!/usr/bin/python

from instruments import *
from quotes import *
import datetime
from google.appengine.ext import db

print 'Content-Type: text/plain'
print ''
print 'Turned off'
exit ()

instrs = Instrument.all ().fetch (1000)
for inst in instrs:
    inst.description = inst.symbol
    inst.put ()
    print '%s processed' % inst.symbol

print 'OK'
